# Start with a build stage that will create the 'tlapid' binary.
FROM golang:1.15.2-alpine3.12 AS builder

# We use the new go module support, so build stuff in a clean directory
# outside GOPATH.
WORKDIR /build

# Add code to the build directory.
COPY . .

# Create the 'tlapid' binary. The netgo tag is needed to create a
RUN cd cmd/tlapid && CGO_ENABLED=0 go build -tags=netgo

# Create a new stage, this is the container we will actually run.
# Use the same distroless image we are already using for tldbwriter.
FROM gcr.io/distroless/static

# Copy the static executable from the builder stage.
COPY --from=builder /build/cmd/tlapid/tlapid /

# Start the service.
ENTRYPOINT ["/tlapid"]
